/*
 * @Date: 2023-12-08 17:59:25
 * @Description: description
 */
export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',
    POPULAR_REFRESH: 'POPULAR_REFRESH',
    POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
    POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
    LOAD_POPULAR_FAIL: 'LOAD_POPULAR_FAIL',
    LOAD_POPULAR_SUCCESS: 'LOAD_POPULAR_SUCCESS',
    POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',
    POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS'
    
  };
  